### PR TITLE
Remove double slashes

### PR DESCRIPTION
**Pull request by bcphung**
There is no more `//` in directory path.

God, I hate it.

### CODE REVIEW

**Comment by bcphung** [comment]
Test build is under building, so, I will take action when it done :smiley: 

P.S. It about an hour of each build :clock11: and there are two of it :snail:

**Comment by boekkooi** [comment]
Hey men Sorry to bud in but i just looked at this fork and maybe you can create a PR for the main repo to remove the double slashes? 

Just a stupid question but why don't you just use https://github.com/boekkooi/openshift-cartridge-nginx and https://github.com/boekkooi/openshift-cartridge-php the last also has [phalcon support](https://github.com/boekkooi/openshift-cartridge-php#phalcon)?
If the problem is that you are running origins you can just customize the builds using the compile script in `usr/compile` is would allow for a single build across all cartridges.

Again sorry for budding in and good luck with the builds.

**Comment by bcphung** [comment]
Hey @boekkooi, that's great you joint :smile: 

You have done a great job, that said, and to me, I'm just a beginner working around. I'm trying to understand the platform so I do some really experiments and this is one of them.

And I don't try to pushing the main repo unless nothing to work out much :)

Again, thank for your great work and your helpful comment!

P.S. I'm teasing memcached, is there any suggest :+1:

**Comment by boekkooi** [comment]
Hey @bcphung great to hear the repo can help you and if you need any help just drop me a mail (warnar:monkey_face:boekkooi.net).

Good luck and don't hesitate to create a PR if you think it helps the repo :smile:

**Comment by bcphung** [comment]
Great, thank you again, @boekkooi :clap:

**Pull request closed without merging**
